/**
 * Generated by scripts/pi/sync-progress-palette.ts from @earendil-works/pi-coding-agent 1.0.0
 * (MIT), commit a13d35a742c6ef8462812a28fbe1d8c8b7431c32. Do not edit directly.
 */
export const SHARED_PROGRESS_ACCENT_ANSI = "\u001b[38;2;167;152;215m";
