/**
 * Generated by scripts/pi/sync-progress-palette.ts from @earendil-works/pi-coding-agent 1.1.0
 * (MIT), commit abe508e1b89912adde45528136c3221eb69acdd7. Do not edit directly.
 */
export const SHARED_PROGRESS_ACCENT_ANSI = "\u001b[38;2;167;152;215m";
