/**
 * Generated by scripts/pi/sync-progress-palette.ts from @earendil-works/pi-coding-agent 1.0.4
 * (MIT), commit 7c10bd4337495ee613f2224843ecdf349b80d1df. Do not edit directly.
 */
export const SHARED_PROGRESS_ACCENT_ANSI = "\u001b[38;2;167;152;215m";
