/**
 * Attributed owned theme resources adapted from @earendil-works/pi-coding-agent 1.0.0 (MIT),
 * commit cd32f7725fdbddbaecdff5b1e68491563394e0ca.
 * Upstream dark.json SHA-256: c11a588b714d35300293079b425fb09a3693d4b2d453585d211b08163c648b75
 * Upstream light.json SHA-256: f590c51c2bc8b238891efd0e983473ed2e2a6487b6692cc1d4b2845165e703f7
 * Modifications: removed upstream schema/export metadata; runtime color data is unchanged.
 */
export const BUILTIN_THEME_RESOURCES = Object.freeze({
  dark: {
    name: "dark",
    appearance: "dark",
    vars: {
      text: "okhsl(234 3% 89%)",
      muted: "okhsl(229 6% 67%)",
      violet: "okhsl(295 50% 67%)",
      blue: "okhsl(232 54% 67%)",
      green: "okhsl(159 59% 67%)",
      red: "okhsl(20 72% 67%)",
      yellow: "okhsl(83 88% 67%)",
      blueBg: "okhsl(233 41% 24%)",
    },
    colors: {
      accent: "violet",
      border: "okhsl(231 57% 65%)",
      borderAccent: "okhsl(295 53% 64%)",
      borderMuted: "okhsl(229 8% 53%)",
      success: "green",
      error: "red",
      warning: "yellow",
      muted: "muted",
      dim: "okhsl(229 8% 56%)",
      text: "text",
      thinkingText: "okhsl(226 7% 65%)",
      selectedBg: "blueBg",
      scrollbarTrack: "okhsl(237 7% 33%)",
      scrollbarThumb: "okhsl(232 7% 65%)",
      searchMatchBg: "okhsl(53 51% 24%)",
      searchMatchText: "muted",
      userMessageBg: "blueBg",
      userMessageText: "text",
      customMessageBg: "okhsl(295 42% 24%)",
      customMessageText: "muted",
      customMessageLabel: "violet",
      toolPendingBg: "okhsl(229 5% 24%)",
      toolSuccessBg: "okhsl(158 46% 25%)",
      toolErrorBg: "okhsl(19 54% 25%)",
      toolTitle: "text",
      toolOutput: "muted",
      mdHeading: "yellow",
      mdLink: "blue",
      mdLinkUrl: "muted",
      mdCode: "violet",
      mdCodeBlock: "green",
      mdCodeBlockBorder: "muted",
      mdQuote: "muted",
      mdQuoteBorder: "muted",
      mdHr: "muted",
      mdListBullet: "violet",
      toolDiffAdded: "green",
      toolDiffRemoved: "red",
      toolDiffContext: "muted",
      syntaxComment: "muted",
      syntaxKeyword: "blue",
      syntaxFunction: "yellow",
      syntaxVariable: "okhsl(202 58% 67%)",
      syntaxString: "okhsl(52 67% 67%)",
      syntaxNumber: "green",
      syntaxType: "violet",
      syntaxOperator: "muted",
      syntaxPunctuation: "muted",
      thinkingOff: "okhsl(229 8% 49%)",
      thinkingMinimal: "okhsl(232 20% 52%)",
      thinkingLow: "okhsl(232 45% 54%)",
      thinkingMedium: "okhsl(263 59% 56%)",
      thinkingHigh: "okhsl(295 73% 59%)",
      thinkingXhigh: "okhsl(337 81% 61%)",
      thinkingMax: "okhsl(20 99% 63%)",
      bashMode: "okhsl(159 64% 65%)",
    },
  },
  light: {
    name: "light",
    appearance: "light",
    vars: {
      text: "okhsl(225 5% 27%)",
      muted: "okhsl(229 8% 47%)",
      violet: "okhsl(295 60% 46%)",
      blue: "okhsl(231 68% 47%)",
      green: "okhsl(159 75% 46%)",
      red: "okhsl(20 91% 47%)",
      yellow: "okhsl(83 99% 47%)",
      blueBg: "okhsl(235 19% 91%)",
    },
    colors: {
      accent: "violet",
      border: "okhsl(231 67% 55%)",
      borderAccent: "okhsl(295 59% 55%)",
      borderMuted: "okhsl(235 7% 66%)",
      success: "green",
      error: "red",
      warning: "yellow",
      muted: "muted",
      dim: "okhsl(229 7% 59%)",
      text: "text",
      thinkingText: "okhsl(234 8% 55%)",
      selectedBg: "blueBg",
      scrollbarTrack: "okhsl(248 3% 90%)",
      scrollbarThumb: "okhsl(226 7% 65%)",
      searchMatchBg: "okhsl(56 22% 91%)",
      searchMatchText: "muted",
      userMessageBg: "blueBg",
      userMessageText: "text",
      customMessageBg: "okhsl(295 25% 91%)",
      customMessageText: "muted",
      customMessageLabel: "violet",
      toolPendingBg: "okhsl(248 3% 91%)",
      toolSuccessBg: "okhsl(156 21% 91%)",
      toolErrorBg: "okhsl(24 23% 91%)",
      toolTitle: "text",
      toolOutput: "muted",
      mdHeading: "yellow",
      mdLink: "blue",
      mdLinkUrl: "muted",
      mdCode: "violet",
      mdCodeBlock: "green",
      mdCodeBlockBorder: "muted",
      mdQuote: "muted",
      mdQuoteBorder: "muted",
      mdHr: "muted",
      mdListBullet: "violet",
      toolDiffAdded: "green",
      toolDiffRemoved: "red",
      toolDiffContext: "muted",
      syntaxComment: "muted",
      syntaxKeyword: "blue",
      syntaxFunction: "yellow",
      syntaxVariable: "okhsl(203 73% 46%)",
      syntaxString: "okhsl(52 84% 46%)",
      syntaxNumber: "green",
      syntaxType: "violet",
      syntaxOperator: "muted",
      syntaxPunctuation: "muted",
      thinkingOff: "okhsl(223 5% 80%)",
      thinkingMinimal: "okhsl(229 14% 78%)",
      thinkingLow: "okhsl(232 33% 76%)",
      thinkingMedium: "okhsl(264 48% 74%)",
      thinkingHigh: "okhsl(295 62% 72%)",
      thinkingXhigh: "okhsl(337 74% 70%)",
      thinkingMax: "okhsl(20 98% 68%)",
      bashMode: "okhsl(159 74% 55%)",
    },
  },
} as const);

export type BuiltinThemeName = keyof typeof BUILTIN_THEME_RESOURCES;

export function isBuiltinThemeName(name: string): name is BuiltinThemeName {
  return Object.hasOwn(BUILTIN_THEME_RESOURCES, name);
}
