import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
// @ts-expect-error — repository governance helper is shipped as JavaScript.
import { readPinnedPiIdentity } from "../governance/pinned-pi-identity.mjs";
import { loadPiTheme } from "../../src/integrations/pi/components/upstream/theme/theme.js";

const repository = fileURLToPath(new URL("../..", import.meta.url));
const targets = [
  resolve(repository, "src/foundation/release/progress-palette.generated.ts"),
  resolve(repository, "packages/a1-install/bin/progress-palette.js"),
] as const;
const pinned = await readPinnedPiIdentity(repository) as { readonly version: string; readonly commit: string };
const accent = loadPiTheme("dark", "truecolor").getFgAnsi("accent");
const source = `/**\n * Generated by scripts/pi/sync-progress-palette.ts from @earendil-works/pi-coding-agent ${pinned.version}\n * (MIT), commit ${pinned.commit}. Do not edit directly.\n */\nexport const SHARED_PROGRESS_ACCENT_ANSI = ${JSON.stringify(accent)};\n`;

if (process.argv.includes("--check")) {
  const stale: string[] = [];
  for (const path of targets) {
    const actual = await readFile(path, "utf8").catch(() => "");
    if (actual !== source) stale.push(path);
  }
  if (stale.length > 0) throw new Error(`progress palette is stale: ${stale.join(", ")}`);
  process.stdout.write("Progress palette matches the pinned Pi accent.\n");
} else {
  await Promise.all(targets.map(async path => await writeFile(path, source)));
  process.stdout.write(`Updated progress palette from Pi ${pinned.version}.\n`);
}
